In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import itertools
import matplotlib.pyplot as plt
%matplotlib inline
from pathlib import Path
import keras
from keras import models
from keras.layers import Dense, Dropout
from keras import optimizers
from keras import losses 
from keras import metrics
from keras.models import Sequential

Using TensorFlow backend.

In [2]:
np.random.seed(7)

In [3]:
data = pd.read_csv('input\PhisingWebsite_datset.csv')

In [4]:
data.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [144]:
data.ndim

2

In [145]:
data.shape

(11055, 31)

In [146]:
data.columns

Index(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [147]:
data.Result.replace([-1 , 1 ], [0 , 1],inplace =True)

In [148]:
pd.isnull(data).sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result                         0
dtype: int64

In [149]:
pd.isna(data).sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result                         0
dtype: int64

In [150]:
x = data.drop('Result',axis =1)
y = data['Result']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [151]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(7738, 30) (7738,) (3317, 30) (3317,)

In [152]:
type(x_train)

pandas.core.frame.DataFrame

In [153]:
type(y_train)

pandas.core.series.Series

In [154]:
y_train = y_train.to_frame()
y_test = y_test.to_frame()

In [155]:
type(y_train)

pandas.core.frame.DataFrame

In [156]:
type(y_test)

pandas.core.frame.DataFrame

In [157]:
x_train.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,RightClick,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report
5138,1,1,-1,-1,1,-1,1,1,-1,1,...,1,1,1,-1,1,-1,1,1,1,1
4404,-1,1,-1,1,-1,-1,-1,1,-1,1,...,1,1,1,-1,-1,1,-1,1,1,1
1829,1,1,1,1,1,-1,-1,1,-1,1,...,1,1,1,1,1,1,-1,1,0,1
8113,1,-1,1,1,1,-1,-1,1,-1,1,...,1,1,1,-1,1,1,1,1,0,1
4765,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,1,-1,1,-1,1,1,-1

In [158]:
y_train.head()

      Result
5138       1
4404       1
1829       1
8113       1
4765       0

In [159]:
train_data = pd.concat([x_train, y_train], axis=1, join='inner')
test_data = pd.concat([x_test, y_test], axis=1, join='inner')

In [160]:
train_data.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
5138,1,1,-1,-1,1,-1,1,1,-1,1,...,1,1,-1,1,-1,1,1,1,1,1
4404,-1,1,-1,1,-1,-1,-1,1,-1,1,...,1,1,-1,-1,1,-1,1,1,1,1
1829,1,1,1,1,1,-1,-1,1,-1,1,...,1,1,1,1,1,-1,1,0,1,1
8113,1,-1,1,1,1,-1,-1,1,-1,1,...,1,1,-1,1,1,1,1,0,1,1
4765,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,1,-1,1,-1,1,1,-1,0

In [161]:
test_data.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
8016,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,...,-1,-1,-1,-1,-1,-1,-1,1,1,0
4546,1,-1,1,1,1,1,1,1,-1,1,...,1,1,1,1,0,-1,1,0,1,1
4482,1,-1,1,-1,1,-1,1,1,-1,1,...,1,1,1,-1,1,-1,1,0,1,1
4534,1,-1,1,1,1,-1,1,1,1,1,...,1,1,1,1,1,-1,1,0,1,1
5909,-1,-1,1,1,1,-1,1,-1,1,1,...,1,1,-1,1,0,1,1,1,-1,0

In [162]:
train_data.to_csv('output/train.csv',index_label='Index')
test_data.to_csv('output/test.csv',index_label='Index')

In [163]:
train_data.describe()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
count,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,...,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000,7738.000000
mean,0.318687,-0.629103,0.739726,0.697596,0.743603,-0.735591,0.054278,0.257948,-0.345309,0.624968,...,0.608943,0.809253,0.063841,0.383303,0.293487,-0.483329,0.726544,0.347894,0.722667,0.560739
std,0.947921,0.770357,0.672952,0.716537,0.668665,0.677470,0.818015,0.908872,0.938550,0.780701,...,0.793265,0.587498,0.998025,0.923682,0.826291,0.875495,0.687164,0.567924,0.691241,0.496329
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,-1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,...,1.000000,1.000000,-1.000000,-1.000000,0.000000,-1.000000,1.000000,0.000000,1.000000,0.000000
50%,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,1.000000,-1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,0.000000,1.000000,1.000000
75%,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [164]:
test_data.describe()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
count,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,...,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000,3317.000000
mean,0.302382,-0.642749,0.736509,0.707567,0.736509,-0.733494,0.086524,0.234549,-0.316853,0.637021,...,0.623756,0.834790,0.055170,0.362677,0.272837,-0.484474,0.709979,0.334941,0.712391,0.548086
std,0.953331,0.756089,0.676530,0.706753,0.676530,0.679798,0.816035,0.918829,0.948618,0.770962,...,0.781737,0.550651,0.998628,0.932055,0.831033,0.874938,0.704329,0.574614,0.701889,0.497757
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,-1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,...,1.000000,1.000000,-1.000000,-1.000000,0.000000,-1.000000,1.000000,0.000000,1.000000,0.000000
50%,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,1.000000,-1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,0.000000,1.000000,1.000000
75%,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [165]:
x_train.dtypes

having_IP_Address              int64
URL_Length                     int64
Shortining_Service             int64
having_At_Symbol               int64
double_slash_redirecting       int64
Prefix_Suffix                  int64
having_Sub_Domain              int64
SSLfinal_State                 int64
Domain_registeration_length    int64
Favicon                        int64
port                           int64
HTTPS_token                    int64
Request_URL                    int64
URL_of_Anchor                  int64
Links_in_tags                  int64
SFH                            int64
Submitting_to_email            int64
Abnormal_URL                   int64
Redirect                       int64
on_mouseover                   int64
RightClick                     int64
popUpWidnow                    int64
Iframe                         int64
age_of_domain                  int64
DNSRecord                      int64
web_traffic                    int64
Page_Rank                      int64
Google_Index                   int64
Links_pointing_to_page         int64
Statistical_report             int64
dtype: object

In [166]:
y_train.dtypes

Result    int64
dtype: object

In [167]:
y_train.head(10)

      Result
5138       1
4404       1
1829       1
8113       1
4765       0
8891       1
3543       1
6259       1
8266       1
8263       1

In [168]:
y_test.head(10)

      Result
8016       0
4546       1
4482       1
4534       1
5909       0
1871       0
6003       1
7198       1
9255       1
4727       1

In [169]:
test_data.groupby('Result').describe()

       Abnormal_URL                                              DNSRecord  \
              count      mean       std  min  25%  50%  75%  max     count
Result
0            1499.0  0.765177  0.644035 -1.0  1.0  1.0  1.0  1.0    1499.0
1            1818.0  0.656766  0.754302 -1.0  1.0  1.0  1.0  1.0    1818.0

                 ...  port      web_traffic                                \
            mean ...   75%  max       count      mean       std  min  25%
Result           ...
0       0.280854 ...   1.0  1.0      1499.0 -0.040694  0.802415 -1.0 -1.0
1       0.430143 ...   1.0  1.0      1818.0  0.531353  0.762607 -1.0  0.0


        50%  75%  max
Result
0       0.0  1.0  1.0
1       1.0  1.0  1.0

[2 rows x 240 columns]

In [170]:
model =Sequential()

In [171]:
model.add(Dense(32, kernel_initializer="uniform", input_dim =30, activation='relu'))
model.add(Dense(32, kernel_initializer="uniform", activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, kernel_initializer="uniform", activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(8,  kernel_initializer="uniform", activation='relu'))
model.add(Dense(1, kernel_initializer="uniform", activation='sigmoid'))

In [172]:
model.compile(
    optimizer=keras.optimizers.Adam(lr =0.001),
    loss= 'binary_crossentropy',
    metrics=['accuracy']
)

In [173]:
model.fit(
    x_train,
    y_train,
    epochs=30,
    validation_data=(x_test, y_test),
    shuffle=True,
    verbose = 2
)

Train on 7738 samples, validate on 3317 samples
Epoch 1/30
 - 4s - loss: 0.5787 - acc: 0.6742 - val_loss: 0.3242 - val_acc: 0.9126
Epoch 2/30
 - 1s - loss: 0.2812 - acc: 0.9045 - val_loss: 0.1925 - val_acc: 0.9264
Epoch 3/30
 - 1s - loss: 0.2210 - acc: 0.9212 - val_loss: 0.1769 - val_acc: 0.9307
Epoch 4/30
 - 1s - loss: 0.1986 - acc: 0.9261 - val_loss: 0.1642 - val_acc: 0.9331
Epoch 5/30
 - 1s - loss: 0.1884 - acc: 0.9312 - val_loss: 0.1588 - val_acc: 0.9340
Epoch 6/30
 - 1s - loss: 0.1701 - acc: 0.9350 - val_loss: 0.1495 - val_acc: 0.9376
Epoch 7/30
 - 1s - loss: 0.1695 - acc: 0.9365 - val_loss: 0.1463 - val_acc: 0.9385
Epoch 8/30
 - 1s - loss: 0.1576 - acc: 0.9399 - val_loss: 0.1382 - val_acc: 0.9406
Epoch 9/30
 - 1s - loss: 0.1470 - acc: 0.9440 - val_loss: 0.1422 - val_acc: 0.9400
Epoch 10/30
 - 1s - loss: 0.1442 - acc: 0.9424 - val_loss: 0.1310 - val_acc: 0.9430
Epoch 11/30
 - 1s - loss: 0.1360 - acc: 0.9470 - val_loss: 0.1293 - val_acc: 0.9430
Epoch 12/30
 - 1s - loss: 0.1290 - acc: 0.9483 - val_loss: 0.1252 - val_acc: 0.9430
Epoch 13/30
 - 1s - loss: 0.1270 - acc: 0.9493 - val_loss: 0.1207 - val_acc: 0.9475
Epoch 14/30
 - 1s - loss: 0.1255 - acc: 0.9501 - val_loss: 0.1234 - val_acc: 0.9448
Epoch 15/30
 - 1s - loss: 0.1221 - acc: 0.9512 - val_loss: 0.1201 - val_acc: 0.9442
Epoch 16/30
 - 1s - loss: 0.1132 - acc: 0.9533 - val_loss: 0.1138 - val_acc: 0.9515
Epoch 17/30
 - 1s - loss: 0.1120 - acc: 0.9561 - val_loss: 0.1168 - val_acc: 0.9494
Epoch 18/30
 - 1s - loss: 0.1092 - acc: 0.9543 - val_loss: 0.1117 - val_acc: 0.9527
Epoch 19/30
 - 1s - loss: 0.1081 - acc: 0.9572 - val_loss: 0.1115 - val_acc: 0.9536
Epoch 20/30
 - 1s - loss: 0.1031 - acc: 0.9593 - val_loss: 0.1100 - val_acc: 0.9503
Epoch 21/30
 - 1s - loss: 0.0994 - acc: 0.9581 - val_loss: 0.1089 - val_acc: 0.9518
Epoch 22/30
 - 1s - loss: 0.0999 - acc: 0.9590 - val_loss: 0.1051 - val_acc: 0.9557
Epoch 23/30
 - 1s - loss: 0.0969 - acc: 0.9605 - val_loss: 0.1332 - val_acc: 0.9469
Epoch 24/30
 - 1s - loss: 0.0947 - acc: 0.9614 - val_loss: 0.1051 - val_acc: 0.9560
Epoch 25/30
 - 1s - loss: 0.0958 - acc: 0.9630 - val_loss: 0.1080 - val_acc: 0.9533
Epoch 26/30
 - 1s - loss: 0.0922 - acc: 0.9629 - val_loss: 0.1059 - val_acc: 0.9578
Epoch 27/30
 - 1s - loss: 0.0911 - acc: 0.9629 - val_loss: 0.1061 - val_acc: 0.9551
Epoch 28/30
 - 1s - loss: 0.0893 - acc: 0.9643 - val_loss: 0.1074 - val_acc: 0.9551
Epoch 29/30
 - 1s - loss: 0.0901 - acc: 0.9623 - val_loss: 0.1042 - val_acc: 0.9614
Epoch 30/30
 - 1s - loss: 0.0857 - acc: 0.9652 - val_loss: 0.1031 - val_acc: 0.9575